language: node_js
node_js:
  - "7"

addons:
  apt_packages:
    - pandoc


before_script:
  - wget https://downloads.sourceforge.net/project/plantuml/plantuml.jar?r=&ts=1494848178&use_mirror=excellmedia /tmp/plantuml.jar
  - npm install -g gulp


script:
  - gulp build
