language: node_js
node_js:
  - "7"

addons:
  apt:
    sources:
      - sourceline: ppa:kbonne/pandoc-plantuml-filter

    packages:
      - pandoc
      - graphviz
      - texlive
      - texlive-latex-recommended
      - texlive-xetex
      - texlive-latex-extra
      - lmodern
      - pandoc-plantuml-filter

before_script:
  - export PATH=$PATH:`pwd`/node_modules/.bin/

script:
  - npm run build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
