language: node_js
node_js:
  - "7"

addons:
  apt_packages:
    - pandoc
    - graphviz
    - texlive
    - texlive-latex-recommended
    - texlive-xetex
    - texlive-latex-extra

before_script:
  - npm install -g gulp
  - export PATH=$PATH:`pwd`/node_modules/.bin/

script:
  - gulp build

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
