@startuml

cloud Internet

node "Server" {
  interface API
  [Business Logic]
  [Data Access] as DA  
  interface IAccommodations
}

package "Mobile app" {
  component [Graphic User\nInterface] as GUI
}

database "Database" {
  [Accommodations]
}

GUI -down-> Internet
Internet -down-( API

[Business Logic] -up- API
DA -- IAccommodations
[Business Logic] --( IAccommodations
DA .. [Accommodations]

User --> GUI



@enduml