@startuml

Actor "User" as u
(Available accomodation list) as accos
(Selected accomodation) as acco
(Chat) as chat

u -right-> accos : Access to
u -right-> accos : Search by filter (price, location, etc..)

accos <-down-> acco
u -down-> acco : choose one accomadation

u -down-> chat : create
acco <-down-> chat

@enduml
